image: maven:3.9.9-eclipse-temurin-17

stages:
  - test
  - build

test-java-project:
  stage: test
  script:
    - mvn test

build-java-project:
  stage: build
  script:
    - mvn -DskipTests package
  artifacts:
    paths:
      - target/
